# Generated by Django 4.1.2 on 2022-12-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referees', '0002_alter_referees_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_date', models.DateField(verbose_name='date played')),
                ('game_result', models.CharField(max_length=100)),
                ('referee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.referees')),
            ],
        ),
    ]
