# Generated by Django 4.1.2 on 2022-12-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_games_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='referee_rating',
            field=models.IntegerField(default=0),
        ),
    ]
