# Generated by Django 4.1.2 on 2022-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_items',
            field=models.ManyToManyField(to='news.news'),
        ),
    ]
