name: Flake8

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Flake8
      run: |
        python -m pip install --upgrade pip
        pip install Flake8
    - name: Lint python codebase
      run: |
        flake8 --ignore=E501 $(git ls-files '*.py')
